### ISSUE TITLE
[Request] Slider indicator that display total slides as 'blobs'

### ISSUE THREAD

**Issue by lew-kni** [Wlada/vue-carousel-3d#87] opened 2018-05-09 10:46 UTC
Hi,

Great plugin. Works seamlessly well with our site. But I've got one request for a future update.

Under many sliders you'll see a set of 'blobs' that display the total number of slides with a single one of them indicating the current active slide.
When clicking on any of these 'blobs', it takes you to the respective slide.

Do you think it would be possible to add in something like this? Or does a solution for this already exist?

For reference, this is a slider i've used in the past.
http://kenwheeler.github.io/slick/

Thanks,

Lew.

**Comment by martijndewit** [comment] 2018-06-28 11:21
Duplicate of #43 
https://github.com/Wlada/vue-carousel-3d/issues/43

**Closed** 2018-06-28 15:24 UTC
